# Lab #3 Exercise
### COMM 4259 <br> <i>Foundations of Machine Learning and AI</i>


© Jingjing Li- Ask for permission for using/quoting: jingjing.li@virginia.edu

## Data Analysis

You need to analyze the fortune500.csv data. This is a data set of Fortune 500 companies spanning over 50 since 1955, put together from Fortune’s public archive.

### 1. Read data and obtain the shape

In [2]:
import pandas as pd
import seaborn as sns

url = "fortune500.csv"

df = pd.read_csv(url)

df.shape

(25131, 5)

### 2. Read top 3 rows

In [3]:
df.head(3)

   Year  Rank         Company  Revenue (in millions)  Profit (in millions)
0  1955     1  General Motors                 9823.5                 806.0
1  1955     2     Exxon Mobil                 5661.4                 584.8
2  1955     3      U.S. Steel                 3250.4                 195.4

### 3. Show the company column (use dot and bracket notation)

In [4]:
df.Company

0               General Motors
1                  Exxon Mobil
2                   U.S. Steel
3             General Electric
4                       Esmark
                 ...
25126          Wm. Wrigley Jr.
25127           Peabody Energy
25128    Wendy's International
25129       Kindred Healthcare
25130     Cincinnati Financial
Name: Company, Length: 25131, dtype: str

In [5]:
df["Company"]

0               General Motors
1                  Exxon Mobil
2                   U.S. Steel
3             General Electric
4                       Esmark
                 ...
25126          Wm. Wrigley Jr.
25127           Peabody Energy
25128    Wendy's International
25129       Kindred Healthcare
25130     Cincinnati Financial
Name: Company, Length: 25131, dtype: str

### 4. Get column names

In [6]:
df.columns

Index(['Year', 'Rank', 'Company', 'Revenue (in millions)',
       'Profit (in millions)'],
      dtype='str')

### 5. Rename column
Rename "'Revenue (in millions)" to be "Revenue_millions" and "Profit (in millions)" to be "Profit_millions"

In [7]:
df.rename(columns = {
    "Revenue (in millions)": "Revenue_millions",
    "Profit (in millions)": "Profit_millions"
}, inplace = True)

df.head()

   Year  Rank           Company  Revenue_millions  Profit_millions
0  1955     1    General Motors            9823.5            806.0
1  1955     2       Exxon Mobil            5661.4            584.8
2  1955     3        U.S. Steel            3250.4            195.4
3  1955     4  General Electric            2959.1            212.6
4  1955     5            Esmark            2510.8             19.1

### 6. Get column types

In [8]:
df.dtypes

Year                  int64
Rank                  int64
Company                 str
Revenue_millions    float64
Profit_millions     float64
dtype: object

### 7. Get the company column use loc function.

In [9]:
df.loc[:, "Company"]

0               General Motors
1                  Exxon Mobil
2                   U.S. Steel
3             General Electric
4                       Esmark
                 ...
25126          Wm. Wrigley Jr.
25127           Peabody Energy
25128    Wendy's International
25129       Kindred Healthcare
25130     Cincinnati Financial
Name: Company, Length: 25131, dtype: str

### 8. Get company name and profit in the first row

In [10]:
df.loc[0, ["Company", "Profit_millions"]]

Company            General Motors
Profit_millions             806.0
Name: 0, dtype: object

### 9. Get all  rows with profit greater than 100 (millions)

In [11]:
df.loc[df.Profit_millions > 100]

,Year,Rank,Company,Revenue_millions,Profit_millions
0,1955,1,General Motors,9823.5,806.0
1,1955,2,Exxon Mobil,5661.4,584.8
2,1955,3,U.S. Steel,3250.4,195.4
3,1955,4,General Electric,2959.1,212.6
7,1955,8,Gulf Oil,1705.3,182.8
...,...,...,...,...,...
25122,2005,492,Brinker International,3707.5,154.0
25124,2005,494,Western & Southern Financial,3694.5,328.0
25126,2005,496,Wm. Wrigley Jr.,3648.6,493.0
25127,2005,497,Peabody Energy,3631.6,175.4
25130,2005,500,Cincinnati Financial,3614.0,584.0

### 10. Get all rows with profit greater than 5,000 (millions) in 2000

### 11. Get the company names with profit greater than 5,000 (millions) in 2000

### 12. Get the last three columns of the second to fifth row (use iloc)

### 13. Describe the Profit and Revenue

### 14. Get the frequency table for the variable Year

### 15. Draw a histogram of profit in the year of 2000

### 16. Create a dataframe for Microsoft and Oracle. Draw a boxplot with the x axis showing two companies and y axis showing profit.

### 17. Draw two histograms side by side showing the profit for Microsoft and Oracle (FacetGrid)

### 18. Draw a line plot for Microsoft and Oracle
Create a lineplot to show Microsoft and Oracle's profit trend by year. Check the lineplot usage about x, y, and hue [here](https://seaborn.pydata.org/generated/seaborn.lineplot.html)